config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  get 'about', to: 'pages#about'

  resources :products
  
  get 'sign_up', to: 'users#new'
  resources :users, except: [:new]
  
  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  delete 'sign_out', to: 'sessions#destroy'
  

end

app/models/product.rb
class Product
  include Mongoid::Document

  belongs_to :user
  
  field :sku, type: String
  field :name, type:String
  field :description, type: String
  field :quantity, type: Float
  field :price, type: Float

  validates :sku, :name, :description, :quantity, :price, :user_id, presence: true
  
end

app/models/user.rb
class User
  include Mongoid::Document
  include ActiveModel::SecurePassword
  
  has_many :products
  
  field :username, type: String
  field :email, type: String
  field :password_digest, type: String

  before_save { self.email = email.downcase }
  
  validates :username, 
    presence: true, 
    uniqueness: { case_sensitive: true }, 
    length: { minimum: 3, maximum: 15 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email,
    presence: true, 
    uniqueness: { case_sensitive: true }, 
    length: { maximum: 150 },
    format: { with: VALID_EMAIL_REGEX }

  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :signed_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def signed_in?
    !!current_user
  end

  def require_user
    if !signed_in?
      flash[:danger] = "Sorry, you must sign in to perform that action!"
      
      redirect_to root_path
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
  end

  def about
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :set_product, only: [:edit, :update, :show, :destroy]

  def index
    @products = Product.page(params[:page]).per(5)
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def create
    @product = Product.new(product_params)
    # TODO User login
    @product.user = User.first

    if @product.save
      flash[:success] = "Product successfully created!"
      redirect_to product_path(@product)
    else
      render 'new'
    end
  end

  def update
    if @product.update(product_params)
      flash[:success] = "Product successfully updated!"
      redirect_to product_path(@product)
    else
      render 'edit'
    end 
  end

  def show
  end

  def destroy
    @product.destroy
    flash[:danger] = "Product successfully deleted!"
    redirect_to products_path
  end

  private
    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:sku, :name, :description, :quantity, :price)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "Welcome, #{user.username}!"
      redirect_to user_path(user)
    else
      flash.now[:danger] = "There was something wrong with you sign in information!"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You have signed out!"
    
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.page(params[:page]).per(5)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = "Welcome to the Challenge #{@user.username}!"
      redirect_to products_path
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      flash[:success] = "Your account was updated successfully."
      redirect_to products_path
    else
      render 'edit'
    end
  end

  def show
    @user = User.find(params[:id])
    @user_products = @user.products.page(params[:page]).per(5)
  end

  private
    def user_params
      params.require(:user).permit(:username, :email, :password)
    end

end

app/helpers/application_helper.rb
require 'digest/md5'

module ApplicationHelper

  def gravatar_for(user, options = { size: 80 })
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    image_src = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(image_src, alt: user.username, class: "img-circle")
  end

end

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="fotter">
    <small>
      Copyright &copy; My first Ruby On Rails App by <a href="https://linkedin.com/in/felipeasouza/" targer="_blank">Felipe Souza</a>
    </small>
    <nav>
      <ul>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "↑Top", "#top" %></li>
      </ul>
    </nav>
  </footer>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%= "#{name}" %>'>
        <a href ="#" class="close" data-dismiss="alert">&#215;</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Challenge", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Products", products_path %></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "New Product", new_product_path %></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if signed_in? %>
          <li><%= link_to "Sign Out", sign_out_path, method: :delete %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="#">Action</a></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Sign In", sign_in_path %></li>
          <li><%= link_to "Sign Up", sign_up_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title id="top">Challenge</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/navigation' %>

  <%= render 'layouts/messages' %>

  <div class="container">
    <%= yield %>
  </div>

  <%= render 'layouts/footer' %>

  <%= debug(params) if Rails.env.development? %>

</body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>

<p>
  <%= link_to '<< Back to Home Page', root_path %>
</p>

app/views/pages/home.html.erb
<div class="center jumbotron">
  <h1>CHALLENGE</h1>
  <%= link_to 'Sign up now!', sign_up_path, class: "btn btn-danger btn-lg btn-xlarge" %>
</div>

app/views/products/_form.html.erb
<%= render "shared/errors", object: @product %>

<div class="row">
  <div class="col-xs-12">
    <%= form_for(@product, :html => { class: "form-horizontal", role: "form" }) do |f| %>
      <div class="form-group">
        <div class="col-sm-2 control-label">
          <%= f.label :sku %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :sku, class: "form-control", placeholder: "Product SKU", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-2 control-label">
          <%= f.label :name %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :name, class: "form-control", placeholder: "Product name" %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-2 control-label">
          <%= f.label :description %>
        </div>
        <div class="col-sm-8">
          <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Product description" %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-2 control-label">
          <%= f.label :quantity %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :quantity, class: "form-control", placeholder: "Product quantity" %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-2 control-label">
          <%= f.label :price %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :price, class: "form-control", placeholder: "Product price" %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-8 col-sm-offset-2">
          <%= f.submit class: "btm btn-primary btn-lg btn-submit" %>
          <%= link_to '<button type="button" class="btm btn-danger btn-lg">Cancel</button>'.html_safe, products_path %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/products/_product.html.erb
<% objects.each do |product| %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="well well-lg">
        <div class="product-title">
          <%= link_to product.name, product_path(product), class: "product-title-link" %>
        </div>
        <div class="product-meta">
          <small>Created by <%= product.user.username %></small>
        </div>
        <div class="product-body">
          <%= truncate(product.description, length: 20) %>
        </div>
        <div class="product-actions">
          <%= link_to 'Edit', edit_product_path(product), class: "btn btn-xs btn-primary" %></td>
          <%= link_to 'Delete', product_path(product), 
                                method: :delete,
                                data: { confirm: "Are you sure you want to delete this product?" },
                                class: "btn btn-xs btn-danger btn-submit" %></td>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1 align="center">Edit a product</h1>

<%= render 'form' %>

app/views/products/index.html.erb
<h1 align="center">Products Listing</h1>

<div align="center">
  <%= paginate @products, theme: "twitter-bootstrap-3" %>
</div>

<%= render "product", objects: @products %>

<div align="center">
  <%= paginate @products, theme: "twitter-bootstrap-3" %>
</div>

app/views/products/new.html.erb
<h1 align="center">Create a product</h1>

<%= render 'form' %>

app/views/products/show.html.erb
<h2 align="center">Showing selected product</h2>

<div class="well col-xs-8 col-xs-offset-2">
  <h4 align="center">Created by:<h4>
  <%= render "users/listing", user_object: @product.user, with_well: false %>
  
  <h4><strong>SKU</strong></h4>
  <%= simple_format(@product.sku) %>
  <hr>
  <h4><strong>Name</strong></h4>
  <%= simple_format(@product.name) %>
  <hr>
  <h4><strong>Description</strong></h4>
  <%= simple_format(@product.description) %>
  <hr>
  <h4><strong>Quantity</strong></h4>
  <%= simple_format(@product.quantity.to_s) %>
  <hr>
  <h4><strong>Price</strong></h4>
  <%= simple_format(@product.price.to_s) %>

  <div class="product-actions">
    <%= link_to 'Edit', edit_product_path(@product), class: "btn btn-xs btn-primary" %>
    <%= link_to 'View All Products', products_path, class: "btn btn-xs btn-success" %>
    <%= link_to 'Delete', product_path(@product), 
                          method: :delete, 
                          data: { confirm: "Are you sure you want to delete this product?" },
                          class: "btn btn-xs btn-danger btn-submit" %>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h2 class="panel-title">
            <%= pluralize(object.errors.count, "error") %>
            prohibited this product from being saved:
          </h2>
          <div class="panel-body">
            <ul>
              <% object.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= render "shared/errors", object: @user %>

<div class="row">
  <div class="col-xs-12">
    <%= form_for(@user, :html => { class: "form-horizontal", role: "form" }) do |f| %>
      <div class="form-group">
        <div class="col-sm-2 control-label">
          <%= f.label :username %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :username, class: "form-control", placeholder: "Enter username", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-2 control-label">
          <%= f.label :email %>
        </div>
        <div class="col-sm-8">
          <%= f.email_field :email, class: "form-control", placeholder: "Enter e-mail" %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-2 control-label">
          <%= f.label :password %>
        </div>
        <div class="col-sm-8">
          <%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-8 col-sm-offset-2">
          <%= f.submit(@user.new_record ? "Sign Up" : "Update", class: "btm btn-primary btn-lg btn-submit") %>
          <%= link_to '<button type="button" class="btm btn-danger btn-lg">Cancel</button>'.html_safe, root_path %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/_listing.html.erb
<% well = with_well ? "well" : "" %>
<ul class="listing">
  <div class="row center">
    <div class='<%= "#{well}" %> col-md-4 col-md-offset-4'>
      <li>
        <%= link_to gravatar_for(user_object), user_path(user_object) %>
      </li>
      <li class="product-title">
        <%= link_to user_object.username, user_path(user_object) %>
      </li>
      <li>
        <small>
          <%= pluralize(user_object.products.count, "product") if user_object.products %>
        </small>
      </li>
    </div>
  </div>
</ul>

app/views/users/edit.html.erb
<h1 align="center">Editing User</h1>

<%= render "form" %>

app/views/users/index.html.erb
<h1 align="center">All Challengers</h1>

<div align="center">
  <%= paginate @users, theme: "twitter-bootstrap-3" %>
  
  <% @users.each do |user| %>
    <%= render "listing", user_object: user, with_well: true %>
  <% end %>
  
  <%= paginate @users, theme: "twitter-bootstrap-3" %>
</div>

app/views/users/new.html.erb
<h1 align="center">Sign Up</h1>

<%= render "form" %>

app/views/users/show.html.erb
<h1 align="center">Welcome to <%= @user.username %>'s page</h1>

<div class="row">
  <div class="col-md-4 col-md-offset-4 center">
    <%= gravatar_for @user, size: 150 %>
  </div>
</div>

<div align="center">
  <h4><%= @user.username %>'s products</h4>
  <%= paginate @user_products, theme: "twitter-bootstrap-3" %>
</div>
  <%= render 'products/product', objects: @user_products %>
<div align="center">
  <%= paginate @user_products, theme: "twitter-bootstrap-3" %>
</div>